apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dev
  namespace: argocd
spec:
  project: dev-platform

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 39.0.0

    helm:
      values: |
        deployment:
          replicas: 1
        # ingressClass:
        #   enabled: true
        #   isDefaultClass: true
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            service.beta.kubernetes.io/azure-load-balancer-ipv4: "10.50.1.150"

        experimental:
          kubernetesGateway:
            enabled: true
            crds:
              enabled: true
        providers:
          kubernetesGateway:
            enabled: true
        # ports:
        #   web:
        #     port: 8080
        #     protocol: TCP
        #     expose:
        #       default: true
        gateway:
          enabled: true
          name: traefik-gateway
          namespace: traefik
          listeners:
            web:
              port: 8080
              protocol: HTTP
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
